### ISSUE TITLE
Updates to `plugin.d.ts` to support Fastify v3

### ISSUE THREAD

**Issue by crcastle** [piscinajs/fastify-piscina#7]
I had to make the following changes to `plugin.d.ts` to be able to use this plugin with Fastify v3 (and typescript 3.9.6). Is this the correct change to support v3? It's a lot simpler, but I'm not sure if it covers all the scenarios the current `plugin.d.ts` does because I'm pretty new to TypeScript. Happy to make a PR, but wanted to get some eyes on this first.

```diff
 import Piscina from "piscina";
-import { Plugin } from "fastify";
-import { ServerResponse, IncomingMessage, Server } from "http";
-import { Http2Server, Http2ServerRequest, Http2ServerResponse } from "http2";
-
-type HttpServer = Server | Http2Server;
-type HttpRequest = IncomingMessage | Http2ServerRequest;
-type HttpResponse = ServerResponse | Http2ServerResponse;
+import { FastifyPlugin } from 'fastify'
 
 type PiscinaOptions = typeof Piscina extends {
   new (options?: infer T): Piscina;
   ? T
   : never;
 
-interface PiscinaPlugin
-  extends Plugin<HttpServer, HttpRequest, HttpResponse, PiscinaOptions> {}
-
-declare const piscinaPlugin: PiscinaPlugin;
-export = piscinaPlugin;
-
 // Most importantly, use declaration merging to add the custom property to the Fastify type system
 declare module "fastify" {
-  interface FastifyInstance<
-    HttpServer = Server,
-    HttpRequest = IncomingMessage,
-    HttpResponse = ServerResponse
-  > {
+  interface FastifyInstance {
     piscina: Piscina;
     runTask: Piscina["runTask"];
   }
 }
+
+declare const fastifyPiscina: FastifyPlugin<PiscinaOptions>
+
+export default fastifyPiscina
```

**Comment by muuvmuuv** [comment]
Any progress?

**Comment by techag** [comment]
Still waiting to get this fixed. @jasnell Since PiscinaPlugin is not `FastifyPlugin instance,`fastify` does not recognize it 

`Argument of type 'PiscinaPlugin' is not assignable to parameter of type 'FastifyPluginCallback<{ filename: string; }, Server>'.       Type 'PiscinaPlugin' provides no match for the signature '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance, Server, IncomingMessage, ServerResponse>, opts: { ...; }, done: (err?: Error | undefined) => void): void'.   Overload 2 of 3, '(plugin: FastifyPluginAsync<{ filename: string; }, Server>, opts?: FastifyRegisterOptions<{ filename: string; }> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.     Argument of type 'PiscinaPlugin' is not assignable to parameter of type 'FastifyPluginAsync<{ filename: string; }, Server>'.       Type 'PiscinaPlugin' provides no match for the signature '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance, Server, IncomingMessage, ServerResponse>, opts: { ...; }): Promise<...>'.   Overload 3 of 3, '(plugin: FastifyPluginCallback<{ filename: string; }, Server> | FastifyPluginAsync<{ filename: string; }, Server> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.     Argument of type 'PiscinaPlugin' is not assignable to parameter of type 'FastifyPluginCallback<{ filename: string; }, Server> | FastifyPluginAsync<{ filename: string; }, Server> | Promise<{ default: FastifyPluginCallback<...>; }> | Promise<...>'.       Type 'PiscinaPlugin' is missing the following properties from type 'Promise<{ default: FastifyPluginAsync<{ filename: string; }, Server>; }>': then, catch, finally, [Symbol.toStringTag]`

**Comment by jasnell** [comment]
Care to open a pull request? I'm fairly swamped at the moment but I can review a PR.
